config/routes.rb
DogHouse::Application.routes.draw do
  root 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :apps, only: [:show] do
    get "list", on: :collection
  end
  namespace :admin do
    resources :users, except: [:show]
    resources :apps do
      patch 'regenerate_key', on: :member
    end
    resources :accounts, except: [:show]
  end
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  has_many :account_apps
  has_many :apps, through: :account_apps
  validates :name, presence: true
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  before_action :require_admin
  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to admin_accounts_path, notice: "New Account has been added!"
    else
      render :new
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to admin_accounts_path, notice: "Account has been updated!"
    else
      render :edit
    end
  end

  def destroy
    Account.find(params[:id]).destroy
    redirect_to admin_accounts_path, notice: "Account has been deleted!"
  end

  private

  def account_params
    params.require(:account).permit(:name, app_ids: [])
  end
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/admin/accounts/_form.html.erb
<%= simple_form_for [:admin, @account] do |f| %>
  <%= f.error_messages %>
  <%= f.input :name %>
  <%= f.association :apps, as: :check_boxes %>
  <%= f.button :submit %>
<% end %>

app/views/admin/accounts/index.html.erb
<%= link_to 'Add Account', new_admin_account_path, class: "btn" %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
    <tr>
      <td><%= account.name %></td>
      <td>
        <%= link_to 'Edit', edit_admin_account_path(account) %>
        <%= link_to 'Delete', admin_account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>