config/routes.rb
DogHouse::Application.routes.draw do
  root 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :apps, only: [:show] do
    get "list", on: :collection
  end
  namespace :admin do
    resources :users, except: [:show]
    resources :apps do
      patch 'regenerate_key', on: :member
    end
    resources :accounts, except: [:show]
  end
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/views/admin/apps/_form.html.erb
<%= simple_form_for [:admin, @app] do |f| %>
  <%= f.error_messages %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.association :accounts, as: :check_boxes %>
  <%= f.button :submit %>
<% end %>

app/views/admin/apps/edit.html.erb
<%= render "form" %>

app/views/admin/apps/index.html.erb
<%= link_to 'Add App', new_admin_app_path, class: 'btn' %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @apps.each do |app| %>
    <tr>
      <td><%= link_to app.name, admin_app_path(app) %></td>
      <td><%= app.url %></td>
      <td>
        <%= link_to 'Edit', edit_admin_app_path(app) %>
        <%= link_to 'Delete', admin_app_path(app), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/apps/new.html.erb
<%= render "form" %>

app/views/admin/apps/show.html.erb
<h1><%= @app.name %></h1>

<dl>
  <dt>URL</dt>
  <dd><%= @app.url %></dd>
  <dt>Secret Key</dt>
  <dd>
    <%= @app.secret_key %>
    <%= link_to "Regenerate Secret Key", regenerate_key_admin_app_path(@app), method: :patch %>
  </dd>
</dl>