config/routes.rb
DogHouse::Application.routes.draw do
  root 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :apps, only: [:show] do
    get "list", on: :collection
  end
  namespace :admin do
    resources :users, except: [:show]
    resources :apps do
      patch 'regenerate_key', on: :member
    end
    resources :accounts, except: [:show]
  end
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :account

  delegate :apps, to: :account

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def send_password_reset
    tokenizer
    UserMailer.password_reset(self).deliver
  end

  def send_new_user_welcome
    tokenizer
    UserMailer.new_user_welcome(self).deliver
  end

  private

  def tokenizer
    generate_token :password_reset_token
    self.password_reset_sent_at = Time.zone.now
    save!
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def create_remember_token
    self.remember_token = self.class.encrypt(self.class.new_remember_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      distribute_user(@user)
      @user.send_new_user_welcome
      redirect_to admin_users_path, notice: "New User has been added!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      distribute_user(@user)
      redirect_to admin_users_path, notice: "User has been updated!"
    else
      render :edit
    end
  end

  def destroy
    # TODO: add archive feature
    User.find(params[:id]).destroy
    redirect_to admin_users_path, notice: "User has been deleted!"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :account_id)
  end

  def distribute_user(user)
    if user.account
      user.apps.each do |app|
        DistributeUserJob.new(user.id, app.id).perform
      end
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
  <%= f.error_messages %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :admin %>
  <%= f.association :account %>
  <%= f.button :submit %>
<% end %>

app/views/admin/users/index.html.erb
<%= link_to 'Add User', new_admin_user_path, class: "btn" %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Account</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin? ? "Admin" : "User" %></td>
      <td><%= user.account ? user.account.name : 'n/a' %></td>
      <td>
        <%= link_to 'Edit', edit_admin_user_path(user) %>
        <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>