config/routes.rb
DogHouse::Application.routes.draw do
  root 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :apps, only: [:show] do
    get "list", on: :collection
  end
  namespace :admin do
    resources :users, except: [:show]
    resources :apps do
      patch 'regenerate_key', on: :member
    end
    resources :accounts, except: [:show]
  end
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <section id="main">
    <header>
      <nav>
        <ul>
          <% if signed_in? %>
            <li><%= link_to "Home", root_path %></li>
            <% if current_user.admin? %>
              <li><%= link_to "Users", admin_users_path %></li>
              <li><%= link_to "Accounts", admin_accounts_path %></li>
              <li><%= link_to "Apps", admin_apps_path %></li>
            <% end %>
            <li><%= link_to "Signout", signout_path, method: :delete %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <div class="alert <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </section>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>